title: Mig Reyes
subtitle: "Designer, 37signals"
author: Mig Reyes
description: Mig is a designer at 37signals focused on making good things for good people.


source: .
destination: public
exclude: [_drafts, _site, public, Gemfile, Gemfile.lock, Rakefile, README.md]

permalink: /:categories/:title
markdown: rdiscount
pygments: true